sonar.organization=jeffsilverface
sonar.projectKey=JeffSilverface_P7

sonar.sources=client/src,server/src
sonar.exclusions=**/node_modules/**,**/dist/**,**/coverage/**
sonar.coverage.exclusions=server/src/logger.ts,server/src/logstashTransport.ts,client/src/services/logger.ts,client/src/services/api.ts,client/src/main.tsx,client/src/services/contactService.ts,client/src/services/organizationService.ts

sonar.javascript.lcov.reportPaths=client/coverage/lcov.info,server/coverage/lcov.info
